### ISSUE TITLE
Missing Rails_helper and spec_helper files

### ISSUE THREAD

**Issue by aisayo** [learn-co-students/rails-form_tag-readme-v-000#918]
The entire spec folder was recently deleted from the repository students clone, leaving them without the rails_helper and spec_helper file.

This will err prompting the student that there are no tests. 

The solution to this was to copy the two files from the solutions branch

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.
We have updated the materials and believe your issue to have been resolved.
If you do not believe that this issue has been addressed, please re-open this issue. 💙
